IPV6: Fix compilation whit unmeet dependendes when disable ipv6
Test with gcc under Fedora 31 and mingw32 under Windows 10

$ CC=x86_64-w64-mingw32-gcc ./configure --host x86_64-w64-mingw32 --disable-embedded-perl --without-perl-modules --enable-static --disable-shared --disable-ipv6
(...)
$ make
(...)
libtool: link: x86_64-w64-mingw32-gcc -g -O2 -fno-strict-aliasing -DNETSNMP_REMOVE_U64 -g -O2 -Umingw32 -Dmingw32=mingw32 -Wall -Wextra -Wstrict-prototypes -Wwrite-strings -Wcast-qual -Wimplicit-fallthrough=2 -Wlogical-op -Wundef -Wno-format-truncation -Wno-missing-field-initializers -Wno-sign-compare -Wno-unused-parameter -o snmpd.exe snmpd.o ../snmplib/winservicerc.o  ./.libs/libnetsnmpagent.a ./.libs/libnetsnmpmibs.a /tmp/net-snmp/agent/.libs/libnetsnmpagent.a -lnetapi32 /tmp/net-snmp/snmplib/.libs/libnetsnmp.a ../snmplib/.libs/libnetsnmp.a -lcrypto -lws2_32 -liphlpapi -lregex -lsnmpapi
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/.libs/libnetsnmp.a(system.o): in function `netsnmp_getaddrinfo':
/tmp/net-snmp/snmplib/system.c:933: undefined reference to `netsnmp_inet_ntop'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/system.c:924: undefined reference to `netsnmp_inet_ntop'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/.libs/libnetsnmp.a(snmpUDPDomain.o): in function `netsnmp_udp_com2SecEntry_create':
/tmp/net-snmp/snmplib/transports/snmpUDPDomain.c:262: undefined reference to `netsnmp_inet_ntop'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/transports/snmpUDPDomain.c:262: undefined reference to `netsnmp_inet_ntop'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/transports/snmpUDPDomain.c:262: undefined reference to `netsnmp_inet_ntop'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/.libs/libnetsnmp.a(snmpUDPDomain.o):/tmp/net-snmp/snmplib/transports/snmpUDPDomain.c:262: more undefined references to `netsnmp_inet_ntop' follow
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/.libs/libnetsnmp.a(snmpUDPDomain.o): in function `netsnmp_udp_parse_security':
/tmp/net-snmp/snmplib/transports/snmpUDPDomain.c:386: undefined reference to `netsnmp_inet_pton'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/transports/snmpUDPDomain.c:386: undefined reference to `netsnmp_inet_pton'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/transports/snmpUDPDomain.c:414: undefined reference to `netsnmp_inet_pton'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/.libs/libnetsnmp.a(snmpUDPDomain.o): in function `netsnmp_udp_getSecName':
/tmp/net-snmp/snmplib/transports/snmpUDPDomain.c:571: undefined reference to `netsnmp_inet_ntop'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/transports/snmpUDPDomain.c:571: undefined reference to `netsnmp_inet_ntop'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/transports/snmpUDPDomain.c:571: undefined reference to `netsnmp_inet_ntop'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/transports/snmpUDPDomain.c:571: undefined reference to `netsnmp_inet_ntop'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/.libs/libnetsnmp.a(snmpIPv4BaseDomain.o): in function `netsnmp_ipv4_fmtaddr':
/tmp/net-snmp/snmplib/transports/snmpIPv4BaseDomain.c:196: undefined reference to `netsnmp_inet_ntop'
/usr/lib/gcc/x86_64-w64-mingw32/9.2.1/../../../../x86_64-w64-mingw32/bin/ld: /tmp/net-snmp/snmplib/.libs/libnetsnmp.a(snmpIPv4BaseDomain.o):/tmp/net-snmp/snmplib/transports/snmpIPv4BaseDomain.c:196: more undefined references to `netsnmp_inet_ntop' follow
collect2: error: ld returned 1 exit status

$ ./configure --with-defaults --disable-shared --enable-static --disable-ipv6
(...)
$ make
(...)
libtool: link: gcc -g -O2 -fno-strict-aliasing -DNETSNMP_REMOVE_U64 -g -O2 -Ulinux -Dlinux=linux -Wall -Wextra -Wstrict-prototypes -Wwrite-strings -Wcast-qual -Wimplicit-fallthrough=2 -Wlogical-op -Wundef -Wno-format-truncation -Wno-missing-field-initializers -Wno-sign-compare -Wno-unused-parameter -o snmpd snmpd.o  ./.libs/libnetsnmpagent.a ./.libs/libnetsnmpmibs.a /tmp/net-snmp/agent/.libs/libnetsnmpagent.a /tmp/net-snmp/snmplib/.libs/libnetsnmp.a -ldl -lrpm -lrpmio ../snmplib/.libs/libnetsnmp.a -lm -lcrypto
/usr/bin/ld: ./.libs/libnetsnmpagent.a(vacm_conf.o): in function `vacm_create_simple':
/tmp/net-snmp/agent/mibgroup/mibII/vacm_conf.c:982: undefined reference to `netsnmp_udp6_parse_security'
/usr/bin/ld: ./.libs/libnetsnmpagent.a(vacm_conf.o): in function `vacm_check_view_contents':
/tmp/net-snmp/agent/mibgroup/mibII/vacm_conf.c:1345: undefined reference to `netsnmp_UDPIPv6Domain'
/usr/bin/ld: /tmp/net-snmp/agent/mibgroup/mibII/vacm_conf.c:1345: undefined reference to `netsnmp_TCPIPv6Domain'
/usr/bin/ld: /tmp/net-snmp/agent/mibgroup/mibII/vacm_conf.c:1348: undefined reference to `netsnmp_udp6_getSecName'